project_id = "cse4104-7a-t03-nutrilens"

[api]
enabled = true
port = 54321
schemas = ["public"]

[functions]
enabled = true

[functions.auth-register]
verify_jwt = false

[functions.auth-login]
verify_jwt = false

[functions.help]
verify_jwt = false
