packages:
  - frontend
  - backend
  - ai-node

allowBuilds:
  esbuild: true
  onnxruntime-node: true
  sharp: true
  workerd: true

onlyBuiltDependencies:
  - esbuild
  - onnxruntime-node
  - sharp
  - workerd
